#!/bin/bash -l

set -e

grep -q "cd\s\+/root/nomad/jobs" /root/.bash_history || fail-message "You have not navigated to /root/nomad/jobs on the Nomad server yet."

grep -q "nomad\s\+job\s\+run\s\+mongodb.nomad" /root/.bash_history || fail-message "You have not run the mongodb.nomad job on the Nomad server yet."

grep -q "nomad\s\+job\s\+status\s\+mongodb" /root/.bash_history || fail-message "You have not checked the status of the mongodb job with the CLI on the Nomad server yet."

grep -q "nomad\s\+job\s\+run\s\+chat-app-light-binary.nomad" /root/.bash_history || fail-message "You have not run the chat-app-light-binary.nomad job on the Nomad server yet."

grep -q "nomad\s\+job\s\+status\s\+chat-app" /root/.bash_history || fail-message "You have not checked the status of the chat-app job on the Nomad server yet."

grep -q "nomad\s\+job\s\+run\s\+nginx.nomad" /root/.bash_history || fail-message "You have not run the nginx.nomad job on the Nomad server yet."

exit 0
