#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Run mongodb Job
nomad job run mongodb.nomad

# Sleep
sleep 30

# Check mongodb job Status
nomad job status mongodb

# Run fabio Job
nomad job run fabio.nomad

# Sleep
sleep 30

# Run chat-app Job
nomad job run chat-app.nomad

# Sleep
sleep 120

# Check chat-app Status
nomad job status chat-app

exit 0
