#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Run mongodb Job
nomad job run mongodb.nomad

# Sleep
sleep 30

# Check mongodb job Status
nomad job status mongodb

# Run chat-app Job
nomad job run chat-app-light-binary.nomad

# Sleep
sleep 120

# Check chat-app Status
nomad job status chat-app

# Run nginx Job
nomad job run nginx.nomad

# Sleep
sleep 30

exit 0
