#!/bin/bash -l

set -e

#
grep -q "cd\s\+/root/nomad/jobs" /root/.bash_history || fail-message "You have not navigated to /root/nomad/jobs on the Nomad server yet."

grep -q "nomad\s\+job\s\+run\s\+webapp.nomad" /root/.bash_history || fail-message "You have not run the webapp.nomad job on the Nomad server yet."

grep -q "nomad\s\+job\s\+status\s\+webapp" /root/.bash_history || fail-message "You have not checked the status of the webapp job with the CLI on the Nomad server yet."

grep -q "nomad\s\+job\s\+run\s\+traefik.nomad" /root/.bash_history || fail-message "You have not run the traefik.nomad job on the Nomad server yet."

grep -q "nomad\s\+job\s\+status\s\+traefik" /root/.bash_history || fail-message "You have not checked the status of the traefik job on the Nomad server yet."

exit 0
