#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Run webapp Job
nomad job run webapp.nomad

# Sleep
sleep 30

# Check webapp job Status
nomad job status webapp

# Run traefik Job
nomad job run traefik.nomad

# Sleep
sleep 12

# Check traefik Status
nomad job status traefik

exit 0
