#!/bin/bash -l

set -e

grep -q "nomad run nomad/mysql.nomad" /root/.bash_history || fail-message "You have not deployed the MySQL job"

grep -q "nomad volume status mysql" /root/.bash_history || fail-message "You have not checked the volume status"

grep -q "mysql -h mysql-server.service.consul -u web -p -D itemcollection" /root/.bash_history || fail-message "You have not connected to the database"

exit 0
