#!/bin/bash -l

# Wait for Instruqt to finish booting the VM
# This is better than doing sleep
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts and options in /etc/resolv.conf
sed -i "/${HOSTNAME}/d" /etc/hosts
sed -i '/options/d' /etc/resolv.conf

# Some pings to estabish connectivity
ping -c 1 nomad-server-1
ping -c 1 nomad-client-1
ping -c 1 nomad-client-2
ping -c 1 nomad-client-3

mkdir /root/nomad

# Write Nomad Server 1 Config
cat <<-EOF > /etc/nomad.d/nomad-server1.hcl
# Setup data dir
data_dir = "/tmp/nomad/server1"

# Give the agent a unique name.
name = "server1"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 1
}

# Consul configuration
consul {
  address = "nomad-server-1:8500"
}
EOF

# Write Consul Server 1 Config
cat <<-EOF > /etc/consul.d/consul-server1.json
{
  "server": true,
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/server1",
  "node_name": "server1",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "0.0.0.0",
  "bootstrap_expect": 1,
  "recursors": [
    "10.64.1.254"
  ]
}
EOF

# Start Consul
systemctl start consul

# Sleep
sleep 15

# Configure Resolved and iptables
cat <<-EOF > /etc/systemd/resolved.conf.d/consul.conf
[Resolve]
DNS=127.0.0.1
DNSSEC=false
Domains=~consul
EOF
iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
systemctl restart systemd-resolved

# Start Nomad
systemctl start nomad

# Install MySQL Client 5.7
apt-get -y update
apt install -y --fix-missing mysql-client-core-5.7

# Sleep
sleep 60

exit 0
