#!/bin/bash -l

# Wait for Instruqt to finish booting the VM
# This is better than doing sleep
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Comment out mapping of 127.0.0.1 to hostname in /etc/hosts
HOSTNAME=$(hostname -s)
sed -i "s/127\.0\.0\.1 ${HOSTNAME}/#127.0.0.1 ${HOSTNAME}/" /etc/hosts

# Write Nomad Client 2 Config
cat <<-EOF > /etc/nomad.d/nomad-client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name
name = "client2"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-2:8500"
}
EOF

# Write Consul Client 2 Config
cat <<-EOF > /etc/consul.d/consul-client2.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client2",
  "node_name": "client2",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "0.0.0.0",
  "retry_join": [
    "nomad-server-1"
  ],
  "recursors": [
    "10.64.1.254"
  ]
}
EOF

# Start Consul
systemctl start consul

# Sleep
sleep 15

# Configure Resolved and iptables
cat <<-EOF > /etc/systemd/resolved.conf.d/consul.conf
[Resolve]
DNS=127.0.0.1
DNSSEC=false
Domains=~consul
EOF
iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
systemctl restart systemd-resolved

# Start Nomad
systemctl start nomad

exit 0
