#!/bin/bash -l

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts and options in /etc/resolv.conf
sed -i "/${HOSTNAME}/d" /etc/hosts
sed -i '/options/d' /etc/resolv.conf

# Some pings to estabish connectivity
ping -c 1 nomad-server-1-east
ping -c 1 nomad-server-1-west
ping -c 1 nomad-client-1-east
ping -c 1 nomad-client-2-east
ping -c 1 nomad-client-1-west
ping -c 1 nomad-client-2-west

# Write Nomad Client 2 Config
cat <<-EOF > /etc/nomad.d/nomad-client2.hcl
region = "west"
datacenter = "west-1"
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name
name = "client2-west"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-2-west:8500"
}
EOF

# Write Consul Client 2 Config
cat <<-EOF > /etc/consul.d/consul-client2.json
{
  "ui": true,
  "license_path": "/var/consul-license.hclic",
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client2",
  "node_name": "client2-west",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "0.0.0.0",
  "retry_join": [
    "nomad-server-1-west"
  ],
  "recursors": [
    "10.64.1.254"
  ]
}
EOF

# Start Consul
systemctl start consul

# Sleep
sleep 10

# Configure Resolved and iptables
cat <<-EOF > /etc/systemd/resolved.conf.d/consul.conf
[Resolve]
DNS=127.0.0.1
Domains=~consul
EOF
iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
systemctl restart systemd-resolved

# Start Nomad
systemctl start nomad

exit 0
