#!/bin/bash -l

set -e

grep -q "nomad agent -dev -bind=0.0.0.0 &" /root/.bash_history || fail-message "You haven't started the development mode Nomad agent yet"

grep -q "nomad node status" /root/.bash_history || fail-message "You haven't checked status of your Nomad node yet."

grep -q "nomad server members" /root/.bash_history || fail-message "You haven't checked the members of your Nomad cluster yet."

exit 0
