#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Run the Nomad agent in Dev mode
nomad agent -dev -bind=0.0.0.0 > nomad.log 2>&1 &

# Sleep
sleep 30

# Get the Nomad node status
nomad node status

# Get the members of the Nomad cluster
nomad server members

exit 0
