#!/bin/bash -l

# Run the Nomad agent in Dev mode
echo -e "nomad agent -dev -bind=0.0.0.0 &" >> /root/.bash_history
nomad agent -dev -bind=0.0.0.0 > nomad.log 2>&1 &

# Get the Nomad node status
echo -e "nomad node status" >> /root/.bash_history
nomad node status

# Get the members of the Nomad cluster
echo -e "nomad server members" >> /root/.bash_history
nomad server members

exit 0
