#!/bin/bash -l

set -e

grep -q 'curl -s --header "X-Nomad-Token: \$NOMAD_TOKEN" http://localhost:4646/v1/operator/scheduler/configuration?pretty' /root/.bash_history || fail-message "You have not checked the status of preemption on the Server yet."

grep -q "cd /root/nomad/jobs" /root/.bash_history || fail-message "You have not navigated to the /root/nomad/jobs directory on the Server yet."

grep -q "nomad job run mongo.nomad" /root/.bash_history || fail-message "You have not run the mongo.nomad job on the Server yet."

grep -q "nomad stop -purge mongo" /root/.bash_history || fail-message "You have not stopped the mongo job on the Server yet."

grep -q 'curl -X POST --header "X-Nomad-Token: \$NOMAD_TOKEN" http://localhost:4646/v1/operator/scheduler/configuration?pretty -d @../scheduler.json' /root/.bash_history || fail-message "You have not enabled preemption on the Server yet."

grep -q "nomad job plan mongo.nomad" /root/.bash_history || fail-message "You have not planned the mongo.nomad job on the Server yet."

mongo_runs=$(grep "nomad job run mongo.nomad" /root/.bash_history | wc -l)
if [ $mongo_runs -lt 2 ]; then
  echo "You did not run the mongo.nomad job a second time after enabling preemption."
  exit 1
fi

exit 0
