#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Check the current scheduler configuration
curl -s --header "X-Nomad-Token: $NOMAD_TOKEN" http://localhost:4646/v1/operator/scheduler/configuration?pretty

# Change directory
cd /root/nomad/jobs

# Run the mongo.nomad job
nomad job run mongo.nomad

# Sleep
sleep 30

# Purge the mongo.nomad job
nomad stop -purge mongo

# Enable Preemption
curl -X POST --header "X-Nomad-Token: $NOMAD_TOKEN" http://localhost:4646/v1/operator/scheduler/configuration?pretty -d @../scheduler.json

# Plan the mongo.nomad job
nomad job plan mongo.nomad

# Run the mongo.nomad job
nomad job run mongo.nomad

# Sleep
sleep 30

exit 0
