#!/bin/bash -l

set -e

grep -q "consul\s\+agent\s\+-config-file\s\+consul-server1.json\s\+>\s\+consul.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your first Consul server yet."

grep -q "nomad\s\+agent\s\+-config\s\+nomad-server1.hcl\s\+>\s\+nomad.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your first Nomad server yet."

exit 0
