#!/bin/bash -l

set -e

grep -q "consul agent -config-file consul-client2.json > consul.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your second Consul client yet."

grep -q "nomad agent -config nomad-client2.hcl > nomad.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your second Nomad client yet."

exit 0
