#!/bin/bash -l

set -e

grep -q "consul agent -config-file consul-server2.json > consul.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your second Consul server yet."

grep -q "nomad agent -config nomad-server2.hcl > nomad.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your second Nomad server yet."

exit 0
