#!/bin/bash -l

set -e

grep -q "consul agent -config-file consul-client1.json > consul.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your first Consul client yet."

grep -q "nomad agent -config nomad-client1.hcl > nomad.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your first Nomad client yet."

exit 0
