#!/bin/bash -l

set -e

grep -q "consul\s\+agent\s\+-config-file\s\+consul-client1.json\s\+>\s\+consul.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your first Consul client yet."

grep -q "nomad\s\+agent\s\+-config\s\+nomad-client1.hcl\s\+>\s\+nomad.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your first Nomad client yet."

exit 0
