#!/bin/bash -l

set -e

grep -q "consul agent -config-file consul-server3.json > consul.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your third Consul server yet."

grep -q "consul members" /root/.bash_history || fail-message "You haven't checked the members of your Consul cluster yet."

grep -q "nomad agent -config nomad-server3.hcl > nomad.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your third Nomad server yet."

grep -q "nomad server members" /root/.bash_history || fail-message "You haven't checked the members of your Nomad cluster yet. Please do this on the Server 3 tab."

grep -q "nomad node status" /root/.bash_history || fail-message "You haven't checked the staus of your Nomad nodes (clients) yet. Please do this on the Server 3 tab."

exit 0
