#!/bin/bash -l

pkill nomad
rm -fr /tmp/nomad

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/nomad-client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name.
name = "client1"

# Enable the client
client {
  enabled = true
}
EOF

# Write Consul Client 1 Config
cat <<-EOF > /root/nomad/consul-client1.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client1",
  "node_name": "client1",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "retry_join": [
    "nomad-server-1",
    "nomad-server-2",
    "nomad-server-3"
  ],
  "ports": {
    "grpc": 8502
  },
  "connect": {
    "enabled": true
  }
}
EOF

# Install CNI plugins
curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.3/cni-plugins-linux-amd64-v0.8.3.tgz
mkdir -p /opt/cni/bin
tar -C /opt/cni/bin -xzf cni-plugins.tgz

# Configure iptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-arptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

exit 0
