#!/bin/bash -l

pkill nomad
rm -fr /tmp/nomad

# Write Nomad Server 1 Config
cat <<-EOF > /root/nomad/nomad-server1.hcl
# Setup data dir
data_dir = "/tmp/nomad/server1"

# Give the agent a unique name.
name = "server1"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
}
EOF

# Write Consul Server 1 Config
cat <<-EOF > /root/nomad/consul-server1.json
{
  "server": true,
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/server1",
  "node_name": "server1",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "bootstrap_expect": 3,
  "retry_join": [
    "nomad-server-2",
    "nomad-server-3"
  ],
  "ports": {
    "grpc": 8502
  },
  "connect": {
    "enabled": true
  }
}
EOF

# Write Nomad Server 2 Config
cat <<-EOF > /root/nomad/nomad-server2.hcl
# Setup data dir
data_dir = "/tmp/nomad/server2"

# Give the agent a unique name.
name = "server2"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
}
EOF

# Write Consul Server 2 Config
cat <<-EOF > /root/nomad/consul-server2.json
{
  "server": true,
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/server2",
  "node_name": "server2",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "bootstrap_expect": 3,
  "retry_join": [
    "nomad-server-1",
    "nomad-server-3"
  ],
  "ports": {
    "grpc": 8502
  },
  "connect": {
    "enabled": true
  }
}
EOF

# Write Nomad Server 3 Config
cat <<-EOF > /root/nomad/nomad-server3.hcl
# Setup data dir
data_dir = "/tmp/nomad/server3"

# Give the agent a unique name.
name = "server3"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
}
EOF

# Write Consul Server 3 Config
cat <<-EOF > /root/nomad/consul-server3.json
{
  "server": true,
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/server3",
  "node_name": "server3",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "bootstrap_expect": 3,
  "retry_join": [
    "nomad-server-1",
    "nomad-server-2"
  ],
  "ports": {
    "grpc": 8502
  },
  "connect": {
    "enabled": true
  }
}
EOF

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/nomad-client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name.
name = "client1"

# Enable the client
client {
  enabled = true
}
EOF

# Write Consul Client 1 Config
cat <<-EOF > /root/nomad/consul-client1.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client1",
  "node_name": "client1",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "retry_join": [
    "nomad-server-1",
    "nomad-server-2",
    "nomad-server-3"
  ]
}
EOF

# Write Nomad Client 2 Config
cat <<-EOF > /root/nomad/nomad-client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name.
name = "client2"

# Enable the client
client {
  enabled = true
}
EOF

# Write Consul Client 2 Config
cat <<-EOF > /root/nomad/consul-client2.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client2",
  "node_name": "client2",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "retry_join": [
    "nomad-server-1",
    "nomad-server-2",
    "nomad-server-3"
  ]
}
EOF

# Install CNI plugins
curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.3/cni-plugins-linux-amd64-v0.8.3.tgz
mkdir -p /opt/cni/bin
tar -C /opt/cni/bin -xzf cni-plugins.tgz

# Configure iptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-arptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

exit 0
