#!/bin/bash -l

pkill nomad
rm -fr /tmp/nomad

# Write Nomad Server 2 Config
cat <<-EOF > /root/nomad/nomad-server2.hcl
# Setup data dir
data_dir = "/tmp/nomad/server2"

# Give the agent a unique name.
name = "server2"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
}
EOF

# Write Consul Server 2 Config
cat <<-EOF > /root/nomad/consul-server2.json
{
  "server": true,
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/server2",
  "node_name": "server2",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "bootstrap_expect": 3,
  "retry_join": [
    "nomad-server-1",
    "nomad-server-3"
  ],
  "ports": {
    "grpc": 8502
  },
  "connect": {
    "enabled": true
  }
}
EOF

# Install CNI plugins
curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.3/cni-plugins-linux-amd64-v0.8.3.tgz
mkdir -p /opt/cni/bin
tar -C /opt/cni/bin -xzf cni-plugins.tgz

# Configure iptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-arptables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

exit 0
