#!/bin/bash -l

cd nomad

# Run the Consul agent
echo -e "consul agent -config-file consul-server3.json > consul.log 2>&1 &" >> /root/.bash_history
consul agent -config-file consul-server3.json > consul.log 2>&1 &

# Check the members of the Consul cluster
sleep 15
echo -e "consul members" >> /root/.bash_history
consul members

# Run the Nomad server
echo -e "nomad agent -config nomad-server3.hcl > nomad.log 2>&1 &" >> /root/.bash_history
nomad agent -config nomad-server3.hcl > nomad.log 2>&1 &

# Check the Nomad cluster members
sleep 15
echo -e "nomad server members" >> /root/.bash_history
nomad server members

# Check the Nomad nodes
echo -e "nomad node status" >> /root/.bash_history
nomad node status

exit 0
