#!/bin/bash -l

cd nomad

# Run the Consul agent
echo -e "consul agent -config-file consul-server2.json > consul.log 2>&1 &" >> /root/.bash_history
consul agent -config-file consul-server2.json > consul.log 2>&1 &

# Run the Nomad server
echo -e "nomad agent -config nomad-server2.hcl > nomad.log 2>&1 &" >> /root/.bash_history
nomad agent -config nomad-server2.hcl > nomad.log 2>&1 &

exit 0
