#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

cd nomad

# Run the Consul agent
consul agent -config-file consul-client1.json > consul.log 2>&1 &

# Sleep
sleep 15

# Run the Nomad agent
nomad agent -config nomad-client1.hcl > nomad.log 2>&1 &

exit 0
