#!/bin/bash -l

set -e

grep -q "nomad version" /root/.bash_history || fail-message "You haven't run 'nomad version' yet."

grep -q "nomad job run -h" /root/.bash_history || grep -q "nomad job run -help" /root/.bash_history || grep -q "nomad job run --help" /root/.bash_history || fail-message "You haven't run 'nomad job run -h' yet."

exit 0
