#!/bin/bash -l

# Generate short version of example job
nomad job init --short

# Change name to redis.nomad
mv example.nomad redis.nomad

# Change name of job
sed -i "s/example/redis/g" redis.nomad

exit 0
