#!/bin/bash -l

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts
HOSTNAME=$(hostname -s)
sed -i "s/127\.0\.0\.1 ${HOSTNAME}/#127.0.0.1 ${HOSTNAME}/" /etc/hosts

# Generate short version of example job
nomad job init --short

# Change name to redis.nomad
mv example.nomad redis.nomad

# Change name of job
sed -i "s/example/redis/g" redis.nomad

exit 0
