#!/bin/bash -l

set -e

gcloud compute scp nomad-server-1:/root/.bash_history /root/.nomad_server_history --strict-host-key-checking no --zone "europe-west1-b"

grep -q "nomad job stop -purge mysql-server" /root/.nomad_server_history || fail-message "You have not stopped the mysql-server job on the Server yet."

grep -q "nomad status" /root/.nomad_server_history || fail-message "You have not checked Nomad's status after stopping the job on the Server yet."

grep -q "cd /root/nomad" /root/.nomad_server_history || fail-message "You have not navigated to the /root/nomad directory on the Server yet."

grep -q "nomad job run mysql.nomad" /root/.nomad_server_history || fail-message "You have not re-run the mysql.nomad job on the Server yet."

grep -q "nomad job status mysql-server" /root/.nomad_server_history || fail-message "You have not checked the status of the mysql-server job after re-running it on the Server yet."

mysql_job_status=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "nomad job status -short mysql-server | grep Status | grep running | wc -l")
if [ $mysql_job_status -ne 1 ]; then
  fail-message "The mysql-server job is not running."
fi

glove_result=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "mysql -h mysql-server.service.consul -u web -ppassword -D itemcollection -s -N -e \"select count(*) from items where name='glove';\"")

if [ $glove_result -ne 1 ]; then
  fail-message "The MySQL table does not contain 'glove' after restarting the Nomad job."
fi

exit 0
