#!/bin/bash -l

set -e

rm /root/.bash_history
touch /root/.bash_history

# Write solve script
cat <<-EOF > /root/nomad/stop-and-restart-mysql.sh
#!/bin/bash -l
#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change Directory
cd /root/nomad

# Stop and Purge the Job
nomad job stop -purge mysql-server

# Sleep
sleep 30

# Check Nomad's status
nomad status

# Rerun the mysql.nomad Job
nomad job run mysql.nomad

# Sleep
sleep 60

# Check the status of the Job
nomad job status mysql-server
EOF

# SCP solve script to nomad-server-1
gcloud compute scp /root/nomad/stop-and-restart-mysql.sh nomad-server-1:/root/nomad/stop-and-restart-mysql.sh --strict-host-key-checking no --zone "europe-west1-b"

# Make solve script executable
gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "chmod +x /root/nomad/stop-and-restart-mysql.sh"

# Purge history on server
gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "rm /root/.bash_history && touch /root/.bash_history"

exit 0
