#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "/root/nomad/stop-and-restart-mysql.sh"

# Sleep
sleep 30

exit 0
