#!/bin/bash -l

# Comment out mapping of 127.0.0.1 to hostname in /etc/hosts
HOSTNAME=$(hostname -s)
sed -i "s/127\.0\.0\.1 ${HOSTNAME}/#127.0.0.1 ${HOSTNAME}/" /etc/hosts

# Hashistack

# Create Hashistack directory
mkdir -p /root/hashistack
chmod -R 755 /root/hashistack

# Consul

# Create Consul directories
mkdir -p /root/hashistack/consul
chmod -R 755 /root/hashistack/consul

# Configure Consul Autocomplete
consul -autocomplete-install
complete -C /usr/local/bin/consul consul

# Write Consul Server Configuation File
cat <<-EOF > /root/hashistack/consul/server.json
{
    "datacenter": "instruqt",
    "log_level": "INFO",
    "data_dir": "/root/hashistack/consul/server",
    "server": true,
    "ui": true,
    "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
    "client_addr": "0.0.0.0",
    "bootstrap_expect": 1,
    "recursors": [
      "10.64.0.254"
    ]
}
EOF

# Write Consul Client Configuation File
cat <<-EOF > /root/hashistack/consul/client.json
{
    "datacenter": "instruqt",
    "log_level": "INFO",
    "data_dir": "/root/hashistack/consul/client",
    "ui": true,
    "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
    "client_addr": "0.0.0.0",
    "retry_interval": "5s",
    "retry_join": [
        "hashistack-server:8301"
    ],
    "recursors": [
      "10.64.0.254"
    ]
}
EOF

# Write the Service Configuration
cat <<-EOF > /etc/systemd/system/consul.service
[Unit]
Description=Consul
Documentation=https://www.consul.io/intro/index.html
Wants=network-online.target
After=network-online.target

[Service]
Restart=on-failure
ExecStart=/usr/local/bin/consul agent -config-file /root/hashistack/consul/server.json
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=SIGTERM
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

# Enable the service
systemctl enable consul
systemctl start consul

# Sleep
sleep 30

# Configure Resolved and iptables
cat <<-EOF > /etc/systemd/resolved.conf.d/consul.conf
[Resolve]
DNS=127.0.0.1
Domains=~consul
EOF
iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
systemctl restart systemd-resolved

# Vault

# Create Vault directories
mkdir -p /root/hashistack/vault
chmod -R 755 /root/hashistack/vault

# Configure Vault Autocomplete
vault -autocomplete-install
complete -C /usr/local/bin/vault vault

# Write server.hcl configuration
cat <<-EOF > /root/hashistack/vault/server.hcl
storage "consul" {}

listener "tcp" {
    address = "0.0.0.0:8200"
    tls_disable = true
}

disable_mlock = true
ui=true
EOF

# Write the Service Configuration
cat <<-EOF > /etc/systemd/system/vault.service
[Unit]
Description=Vault
Documentation=https://www.vaultproject.io/
Requires=network-online.target
After=network-online.target

[Service]
Restart=on-failure
Environment=GOMAXPROCS=nproc
ExecStart=/usr/local/bin/vault server -config /root/hashistack/vault/server.hcl
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=SIGTERM
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

# Enable the service
systemctl enable vault
systemctl start vault

# Sleep 10 seconds
sleep 30

# Initialize Vault server
vault operator init -key-shares=1 -key-threshold=1 > /root/hashistack/vault/init.log

# Extract root token and unseal key from init.log
token=$(sed -n 3p /root/hashistack/vault/init.log | cut -d':' -f2 | cut -d' ' -f2)
unseal_key=$(sed -n 1p /root/hashistack/vault/init.log | cut -d':' -f2 | cut -d' ' -f2)

# Write token to /root/token
echo $token > /root/hashistack/vault/token

# Write unseal key to /root/unseal_key
echo $unseal_key > /root/hashistack/vault/unseal_key

# Export VAULT_TOKEN to the bash environment
echo -e "export VAULT_TOKEN=$token" >> /root/.bash_profile

# Unseal Vault server
vault operator unseal $unseal_key

# Nomad

# Create Nomad directory
mkdir -p /root/hashistack/nomad
# touch /root/hashistack/nomad/nomad.log
chmod -R 755 /root/hashistack/nomad
mkdir -p /root/hashistack/nomad/server

# Configure Nomad Autocomplete
nomad -autocomplete-install
complete -C /usr/local/bin/nomad nomad

# Write Server main config file
cat <<-EOF > /root/hashistack/nomad/server.hcl
# Set the Datacenter
datacenter = "instruqt"
data_dir = "/root/hashistack/nomad/server"

# Setup the bind address
bind_addr = "0.0.0.0"

# Enable the server
server {
    enabled = true
    bootstrap_expect = 1
}

# Consul
consul {
    address = "127.0.0.1:8500"
}

# Vault
vault {
    enabled = false
    address = "http://active.vault.service.consul:8200"
    task_token_ttl = "1h"
    create_from_role = "nomad-cluster"
    token = "<your nomad server token>"
}
EOF

# Write copy of Nomad client.hcl to server
cat <<-EOF > /root/hashistack/nomad/client.hcl
# Set the Datacenter
datacenter = "instruqt"
data_dir = "/root/hashistack/nomad/client"

# Setup the bind address
bind_addr = "0.0.0.0"

# Enable the client
client {
    enabled = true
    servers = ["hashistack-server"]
}

# Consul
consul {
    address = "127.0.0.1:8500"
}

# Vault
vault {
    enabled = true
    address = "http://active.vault.service.consul:8200"
}
EOF

# Write the Service Configuration
cat <<-EOF > /etc/systemd/system/nomad.service
[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/
Wants=network-online.target
After=network-online.target

# If you are running Consul, please uncomment following Wants/After configs.
# Assuming your Consul service unit name is "consul"
Wants=consul.service
After=consul.service

[Service]
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nomad agent -config /root/hashistack/nomad/server.hcl
KillMode=process
KillSignal=SIGINT
LimitNOFILE=infinity
LimitNPROC=infinity
Restart=on-failure
RestartSec=2
StartLimitBurst=3
StartLimitInterval=10
TasksMax=infinity
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

# Enable the service
systemctl enable nomad
systemctl start nomad

# Check host connections
declare -i i=0
declare -i Port=22
declare -a HostArray=("hashistack-client-1" "hashistack-client-2")
for Host in ${HostArray[@]}; do
  while [ $i -lt 5 ]; do
    $(nc -z -w3 $Host $Port) && break || echo "Port $Port is unreachable on $Host"
    ((i++)) || true
    if [ $i -eq 5 ]; then
      exit 1
    fi
    sleep 6
  done
done

ssh -o StrictHostKeyChecking=no hashistack-client-1 << ENDSSH
systemctl restart systemd-resolved
ENDSSH

ssh -o StrictHostKeyChecking=no hashistack-client-1 << ENDSSH
for i in 1 2 3 4 5 6
do
  vault_status=$(vault status | grep Sealed | grep false | wc -l)
  if [ \$vault_status -eq 1 ]
  then
    break
  fi
  sleep 10
  systemctl restart systemd-resolved
done
ENDSSH

ssh -o StrictHostKeyChecking=no hashistack-client-2 << ENDSSH
systemctl restart systemd-resolved
ENDSSH

ssh -o StrictHostKeyChecking=no hashistack-client-2 << ENDSSH
for i in 1 2 3 4 5 6
do
  vault_status=$(vault status | grep Sealed | grep false | wc -l)
  if [ \$vault_status -eq 1 ]
  then
    break
  fi
  sleep 10
  systemctl restart systemd-resolved
done
ENDSSH

exit 0
