#!/bin/bash -l

set -e

grep -q "cd /home/nomad/nomad/jobs" /home/nomad/.bash_history || fail-message "You have not navigated to the /home/nomad/nomad/jobs directory on the Server yet."

grep -q "export NOMAD_TOKEN=\$(cat /home/nomad/nomad/acls/alice-token.txt | grep Secret | cut -d' ' -f7)" /home/nomad/.bash_history || fail-message "You have not exported Alice's ACL token on the Server yet."

grep -q "nomad quota status dev" /home/nomad/.bash_history || fail-message "You have not checked the status of the dev resoure quota on the Server yet."

grep -q "nomad job run website-dev.nomad" /home/nomad/.bash_history || fail-message "You have not run the website-dev.nomad job on the Server yet."

grep -q "nomad job status -namespace=dev website" /home/nomad/.bash_history || fail-message "You have not checked the status of the website job in the dev namespace on the Server yet."

dev_quota_checks=$(grep "nomad quota status dev" /home/nomad/.bash_history | wc -l)
if [ $dev_quota_checks -lt 2 ]; then
  fail-message "You have not checked the status of the dev resource quota a second time after running the website job in the dev namespace."
fi

grep -q "export NOMAD_TOKEN=\$(cat /home/nomad/nomad/acls/bob-token.txt | grep Secret | cut -d' ' -f7)" /home/nomad/.bash_history || fail-message "You have not exported Bob's ACL token on the Server yet."

grep -q "nomad quota status qa" /home/nomad/.bash_history || fail-message "You have not checked the status of the qa resource quota on the Server yet."

grep -q "nomad job run website-qa.nomad" /home/nomad/.bash_history || fail-message "You have not run the website-qa.nomad job on the Server yet."

grep -q "nomad job stop -namespace=qa webserver-test" /home/nomad/.bash_history || fail-message "You have not stopped the webserver-test job on the Server yet."

# Set the bootstrap ACL token
export NOMAD_TOKEN=$(cat /home/nomad/nomad/acls/bootstrap.txt | grep Secret | cut -d' ' -f7)

# Verify that all allocations for website in qa are healthy
qa_website_healthy=$(nomad job status -namespace=qa website | grep Deployed -A3 | grep "2        2       2" | wc -l)
if [ $qa_website_healthy -ne 2 ]; then
  fail-message "The website job in the qa namespace does not have 4 healthy allocations yet."
fi

exit 0
