#!/bin/bash -l

set -e

# Check status of MySQL job
mysql_status=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "nomad job status mysql-server | grep Deployed -A2 | grep 'mysql-server  1        1       1' | wc -l")

if [ $mysql_status -ne 1 ]; then
  fail-message "'nomad job status mysql-server' does not show a healthy allocation of the mysql job."
fi

exit 0
