#!/bin/bash -l

set -e

# Write MySQL Job to Cloud Client
cat <<-EOF > /root/nomad/mysql.nomad
job "mysql-server" {
  datacenters = ["dc1"]
  type        = "service"

  group "mysql-server" {
    count = 1

    task "mysql-server" {
      driver = "docker"

      env {
        MYSQL_ROOT_PASSWORD = "password"
      }

      config {
        image = "rberlind/mysql-demo:latest"

        port_map {
          db = 3306
        }

        volumes = [
          "mysql:/var/lib/mysql",
        ]

        volume_driver = "pxd"
      }

      resources {
        cpu    = 500
        memory = 1024

        network {
          port "db" {
            static = 3306
          }
        }
      }

      service {
        name = "mysql-server"
        port = "db"

        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
EOF

# SCP mysql.nomad to Nomad Server
gcloud compute scp /root/nomad/mysql.nomad nomad-server-1:/root/nomad/mysql.nomad --strict-host-key-checking no --zone "europe-west1-b"

exit 0
