#!/bin/bash -l

set -e

grep -q "consul members" /root/.bash_history || fail-message "You have not run 'consul members' on the Server yet."

grep -q "nomad server members" /root/.bash_history || fail-message "You have not run 'nomad server members' on the Server yet."

grep -q "nomad node status" /root/.bash_history || fail-message "You have not run 'nomad node status' on the Server yet."

consul_clients=$(consul members | grep alive | wc -l)
if [ $consul_clients -ne 4 ]; then
  echo "There are not 4 running Consul clients."
  exit 1
fi

nomad_servers=$(nomad server members | grep alive | wc -l)
if [ $nomad_servers -ne 1 ]; then
  echo "The Nomad servers is not running."
  exit 1
fi

nomad_clients=$(nomad node status | grep ready | wc -l)
if [ $nomad_clients -ne 3 ]; then
  echo "There are not 3 running Nomad clients."
  exit 1
fi

exit 0
