#!/bin/bash -l

set -e

grep -q "count\s\+=\s\+3" /root/nomad/example.nomad || fail-message "You have not set the count to 3 in example.nomad yet."

grep -q "cd\s\+nomad" /root/.bash_history || fail-message "You have not navigated to the nomad directory yet."

grep -q "nomad\s\+job\s\+plan\s\+example.nomad" /root/.bash_history || fail-message "You have not planned the Nomad job yet."

grep -q "nomad\s\+job\s\+run\s\+-check-index.*example.nomad" /root/.bash_history || fail-message "You have not run the planned Nomad job yet or forgot to use the '-check-index' argument."

grep -q "nomad\s\+job\s\+stop\s\+example" /root/.bash_history || fail-message "You have not stopped the job with the Nomad CLI yet."

exit 0
