#!/bin/bash -l

# CD to the Nomad directory
echo -e "cd nomad" >> /root/.bash_history
cd nomad

# Plan the job
echo -e "nomad plan example.nomad" >> /root/.bash_history
nomad plan example.nomad > planjob.log

# Extract the job modify index
job_modify_index=$(sed -n 1p planjob.log | cut -d'"' -f2)

# Run the job
echo -e "nomad run -check-index $job_modify_index example.nomad" >> /root/.bash_history
nomad run -check-index $job_modify_index example.nomad

# Stop the job
echo -e "nomad job stop example" >> /root/.bash_history
nomad job stop example

exit 0
