#!/bin/bash -l

# Create Token Role
echo -e "nomad run /root/hashistack/nomad/db.nomad" >> /root/.bash_history
nomad run /root/hashistack/nomad/db.nomad

# Write the Nomad policy to Vault
echo -e "nomad status database" >> /root/.bash_history
nomad status postgres-nomad-demo

exit 0