#!/bin/bash -l

set -e

# Get Nomad job status
sshpass -e ssh hashistack@$nomad_server_ip 'nomad job status' > nomad_jobs.txt

# Find running jobs
running_jobs=$(cat nomad_jobs.txt | grep running | wc -l)

# Check running jobs
if [ $running_jobs -lt 3 ]; then
  fail-message "'nomad job status' does not show at least 3 running Nomad jobs."
fi

# Get batchjob dispatches
sshpass -e ssh hashistack@$nomad_server_ip 'nomad job status batchjob' > nomad_batchjob_dispatches.txt

# Find dispatches
dispatched_jobs=$(cat nomad_batchjob_dispatches.txt | grep "batchjob/dispatch" | wc -l)

# Check dispatched jobs
if [ $dispatched_jobs -lt 1 ]; then
  fail-message "You have not yet dispatched an instance of the batchjob yet."
fi

exit 0
