#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Sleep
sleep 30

# Run Windows IIS Job
sshpass -e ssh hashistack@$nomad_server_ip 'nomad job run c:\Users\hashistack\nomad\iis.nomad'

# Run Jenkins Job
sshpass -e ssh hashistack@$nomad_server_ip 'nomad job run c:\Users\hashistack\nomad\jenkins.nomad'

# Run DotNet Batch Job
sshpass -e ssh hashistack@$nomad_server_ip 'nomad job run batchjob.nomad'

# Sleep
sleep 30

# Dispatch an instance of the batchjob
sshpass -e ssh hashistack@$nomad_server_ip 'nomad job dispatch -meta TTL=120 batchjob'

# Sleep
sleep 150

exit 0
