#!/bin/bash -l

set -e

grep -q "nomad\s\+job\s\+status" /root/.bash_history || fail-message "You haven't run 'nomad job status' on Server 2 yet."

grep -q "nomad\s\+agent-info" /root/.bash_history || fail-message "You haven't run 'nomad agent-info' on Server 2 yet."

grep -q "export\s\+NOMAD_TOKEN" /root/.bash_history || fail-message "You haven't exported the admin token on Server 2 yet."


exit 0
