#!/bin/bash -l

set -e

grep -q "export\s\+NOMAD_TOKEN" /root/.bash_history || fail-message "You haven't exported the admin token on Server 1 yet."

grep -q "nomad\s\+acl\s\+policy\s\+delete\s\+anonymous" /root/.bash_history || fail-message "You haven't deleted the anonymous policy on Server 1 yet."

grep -q "nomad\s\+acl\s\+policy\s\+apply .* devRO\s\+dev_policy.hcl" /root/.bash_history || fail-message "You haven't created the devRO ACL policy on Server 1 yet."

grep -q "nomad\s\+acl\s\+policy\s\+apply .* opsRW\s\+ops_policy.hcl" /root/.bash_history || fail-message "You haven't created the opsRW ACL policy on Server 1 yet."

grep -q "nomad\s\+acl\s\+policy\s\+list" /root/.bash_history || fail-message "You haven't listed your ACL policies on Server 1 yet."

grep -q "nomad\s\+acl\s\+token\s\+create .*Dev\s\+RO.*" /root/.bash_history || fail-message "You haven't created the Dev RO token on Server 1 yet."

grep -q "nomad\s\+acl\s\+token\s\+create .*Ops RW.*" /root/.bash_history || fail-message "You haven't created the Ops RW token on Server 1 yet."

grep -q "nomad\s\+acl\s\+token\s\+list" /root/.bash_history || fail-message "You haven't listed your ACL tokens on Server 1 yet."

exit 0
