#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

scp -oStrictHostKeyChecking=no nomad-server-1:/root/nomad/devro_token.txt /root/nomad/devro_token.txt

export NOMAD_TOKEN=`cat /root/nomad/devro_token.txt | grep Secret | awk '{print $4}'`

nomad job status

nomad agent-info

exit 0
