#!/bin/bash -l

set -e

grep -q "vault secrets enable database" /root/.bash_history || fail-message "You haven't enabled Vault's database secrets engine yet."

database_enabled=$(vault secrets list | grep database | wc -l)
if [ "$database_enabled" -ne "1" ]; then
  fail-message "You have not yet enabled Vault's database secrets engine yet."
fi

grep -q "vault write database/config/postgresql @connection.json" /root/.bash_history || fail-message "You haven't created the database connection yet."

grep -q "vault write database/roles/accessdb db_name=postgresql creation_statements=@accessdb.sql default_ttl=1h max_ttl=24h" /root/.bash_history || fail-message "You haven't created the role yet."

grep -q "vault read database/creds/accessdb" /root/.bash_history || fail-message "You haven't created the database credentials yet."

can_read_db_creds=$(vault read database/creds/accessdb | grep username | wc -l)
if [ "$can_read_db_creds" -ne "1" ]; then
  fail-message "The accessdb database credentials cannot be read yet."
fi

grep -q "vault policy write access-tables access-tables-policy.hcl" /root/.bash_history || fail-message "You haven't created the access-table policy yet."

vault policy read access-tables
if [ "$?" -ne "0" ]; then
  fail-message "The Vault policy access-tables does not exist yet."
fi

exit 0
