#!/bin/bash -l

set -e

# Check that the fabio.nomad job was run
grep -q "nomad job run fabio.nomad" /root/.bash_history || fail-message "You haven't run the fabio.nomad job yet."

# Check that the prometheus1.nomad job was run
grep -q "nomad job run prometheus1.nomad" /root/.bash_history || fail-message "You haven't run the prometheus1.nomad job yet."

# Check that the status of the fabio job was checked
grep -q "nomad job status fabio" /root/.bash_history || fail-message "You haven't checked the status of the fabio job yet."

# Check that the status of the prometheus job was checked
grep -q "nomad job status prometheus" /root/.bash_history || fail-message "You haven't checked the status of the prometheus job yet."

exit 0
