#!/bin/bash -l

set -e

grep -q "nomad\s\+run\s\+/root/hashistack/nomad/web.nomad" /root/.bash_history || fail-message "You haven't deployed your application yet."

web_status=$(nomad status web | grep "Status .* running" | wc -l)
if [ "$web_status" -ne "1" ]; then
  fail-message "The Nomad web job is not running yet."
fi

grep -q "dig\s\++short\s\+SRV\s\+web.service.consul." /root/.bash_history || fail-message "You haven't used dig to find a record yet."

grep -qE "curl.*http://web.service.consul:3000/api.*|.*jq" /root/.bash_history || fail-message "You haven't curled your application yet."

products_length=$(curl http://web.service.consul:3000/api | jq '. | length')
if [ "$products_length" -ne "6" ]; then
  fail-message "The web application is not showing all 6 HashiCorp products."
fi

exit 0
