#!/bin/bash -l

set -e

# Write the Nomad Application Job
cat <<-EOF > /root/hashistack/nomad/web.nomad
job "web" {
  datacenters = ["instruqt"]
  group "demo" {

    network {
      port "http" {
        static = 3000
        to     = 3000
      }
    }

    task "server" {
      driver = "docker"
      constraint {
        attribute = "\${node.unique.name}"
        value     = "hashistack-client-1"
      }
      vault {
        policies = ["access-tables"]
      }
      config {
        image = "pgryzan/demo-web:latest"
        ports = ["http"]
      }
      template {
        data = <<EOT
{{ with service "database" }}
{{ with index . 0 }}
  DB_HOST="{{ .Address }}"
  DB_PORT="{{ .Port }}"
{{ end }}
{{ end }}
{{ with secret "database/creds/accessdb" }}
  DB_USERNAME="{{ .Data.username }}"
  DB_PASSWORD="{{ .Data.password }}"
{{ end }}
EOT
        destination = "secrets/file.env"
        env         = true
      }

      service {
        name = "web"
        port = "http"
        tags = [
          "urlprefix-/",
        ]
        check {
          type     = "tcp"
          interval = "2s"
          timeout  = "2s"
        }
      }
    }
  }
}
EOF

exit 0
