#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Deploy the Application
nomad run /root/hashistack/nomad/web.nomad

# Sleep
sleep 60

# Dig the Application
dig +short SRV web.service.consul.

# Curl the Application
curl -s http://web.service.consul:3000/api | tee /dev/fd/2 | jq .

exit 0
