#!/bin/bash -l

set -e

# Write Server main config file
cat <<-EOF > /root/hashistack/nomad/db.nomad
job "database" {
  datacenters = ["instruqt"]

  group "db" {

    network {
      port "db" {
        static = 5432
        to     = 5432
      }
    }

    task "server" {
      driver = "docker"

      config {
        image = "pgryzan/demo-db:latest"
        ports = ["db"]
      }

      service {
        name = "database"
        port = "db"

        check {
          type     = "tcp"
          interval = "2s"
          timeout  = "2s"
        }
      }
    }
  }
}
EOF

exit 0
