#!/bin/bash -l

echo 'shopt -s histappend' >> /home/nomad/.bashrc
echo 'PROMPT_COMMAND="history -a;$PROMPT_COMMAND"' >> /home/nomad/.bashrc

# Write Nomad Client 3 Config
cat <<-EOF > /etc/nomad.d/nomad-client3.hcl
# Setup data dir
data_dir = "/tmp/nomad/client3"

# Give the agent a unique name
name = "client3"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-3:8500"
}
EOF

# Write Consul Client 3 Config
cat <<-EOF > /etc/consul.d/consul-client3.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client3",
  "node_name": "client3",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "retry_join": [
    "nomad-server-1"
  ],
  "connect": {
    "enabled": true
  }
}
EOF

# Start Consul
systemctl start consul

# Sleep
sleep 15

# Start Nomad
systemctl start nomad

# Set the working directory
set-workdir /home/nomad

exit 0
