#!/bin/bash -l

mkdir /root/nomad

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts and options in /etc/resolv.conf
sed -i "/${HOSTNAME}/d" /etc/hosts
sed -i '/options/d' /etc/resolv.conf

# Some pings to estabish connectivity
ping -c 1 nomad-server-1
ping -c 1 nomad-client-1
ping -c 1 nomad-client-2
ping -c 1 nomad-client-3

# Write Nomad Client 1 Config
cat <<-EOF > /etc/nomad.d/nomad-client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name.
name = "client1"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-1:8500"
}
EOF

# Write Consul Client 1 Config
cat <<-EOF > /etc/consul.d/consul-client1.json
{
  "ui": true,
  "license_path": "/var/consul-license.hclic",
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client1",
  "node_name": "client1",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "retry_join": [
    "nomad-server-1"
  ],
  "connect": {
    "enabled": true
  }
}
EOF

# Start Consul
systemctl start consul

# Sleep
sleep 15

# Start Nomad
systemctl start nomad

# Set the working directory
set-workdir /root/nomad

exit 0
