#!/bin/bash -l

#Enable bash history
HISTFILE=/home/nomad/.bash_history
set -o history

# Change owner to nomad
touch /home/nomad/.bash_history
chown nomad:nomad /home/nomad/.bash_history

# Run consul members
consul members

# Run nomad server members
nomad server members

# Run nomad node status
nomad node status

exit 0
