#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Run consul members
consul members

# Run nomad server members
nomad server members

# Run nomad node status
nomad node status

exit 0
