#!/bin/bash -l
#Enable bash history
HISTFILE=~/.bash_history
set -o history

#Work Through Nomad

cd /root/nomad
nomad acl bootstrap > /root/nomad/acl_token.txt

export NOMAD_TOKEN=`cat /root/nomad/acl_token.txt | grep Secret | awk '{print $4}'`

curl --request POST --data @anonymous.json -H "X-Nomad-Token: $NOMAD_TOKEN" http://localhost:4646/v1/acl/policy/anonymous

curl http://localhost:4646/v1/jobs

nomad server members

nomad node status

exit 0
