#!/bin/bash -l
mkdir /tmp/nomad_test
cd /tmp/nomad_test
nomad acl bootstrap > acl_token.txt
cat <<-EOF > /tmp/nomad_test/anonymous.json
{
    "Name": "anonymous",
    "Description": "Allow read-only access for anonymous requests",
    "Rules": "
        namespace \"default\" {
            policy = \"read\"
        }
        agent {
            policy = \"read\"
        }
        node {
            policy = \"read\"
        }
    "
}
EOF

export NOMAD_TOKEN=`cat acl_token.txt | grep Secret | awk '{print $4}'`

curl --request POST --data @anonymous.json -H "X-Nomad-Token: $NOMAD_TOKEN" http://localhost:4646/v1/acl/policy/anonymous

curl http://localhost:4646/v1/jobs

nomad server members

nomad node status

exit 0