#!/bin/bash -l

set -e

grep -q "systemctl restart nomad" /root/.bash_history || fail-message "You have not restarted the Server yet."

grep -q "nomad job status" /root/.bash_history || fail-message "You have not run 'nomad job status' yet."

grep -q "cat /tmp/nomad/server1/audit/audit.log | jq ." /root/.bash_history || fail-message "You have not examined the audit log yet."

exit 0
