#!/bin/bash -l

# Add ACL stanza to nomad-client3.hcl config
cat <<-EOF >> /etc/nomad.d/nomad-client3.hcl

# Enable Auditing
audit {
  enabled = true
}
EOF

mkdir -p /tmp/nomad/client3/audit
touch /tmp/nomad/client3/audit/audit.log
chmod -R 777 /tmp/nomad

exit 0
