#!/bin/bash -l

# Add ACL stanza to nomad-client1.hcl config
cat <<-EOF >> /etc/nomad.d/nomad-client1.hcl

# Enable Auditing
audit {
  enabled = true
}
EOF

mkdir -p /tmp/nomad/client1/audit
touch /tmp/nomad/client1/audit/audit.log
chmod -R 777 /tmp/nomad

exit 0
