#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# cd to nomad directory
cd nomad

# Run the webserver.nomad job
nomad job run webserver.nomad

# Check the status of the webserver job
nomad job status webserver

# Stop the webserver job
nomad job stop webserver

# Re-run the webserver job
nomad job run webserver.nomad

exit 0
