#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# CD to the Nomad directory
cd nomad

# Run the job
nomad job run example.nomad > runjob.log

# Extract evaluation and allocation IDs
eval_id=$(sed -n 1p runjob.log | cut -d'"' -f2)
alloc_id=$(sed -n 3p runjob.log | cut -d'"' -f2)

# Check the job status
nomad job status example

# Check the evaluation status
nomad eval status $eval_id

# Check the allocation status
nomad alloc status $alloc_id

# Inspect the redis task logs from the job
nomad alloc logs $alloc_id redis

exit 0
