#!/bin/bash -l

# Write multi-region job spec
cat <<-EOF > /root/nomad/jobs/multi-redis.nomad
job "example" {

  multiregion {

    strategy {
      max_parallel = 1
      on_failure   = "fail_all"
    }

    region "west" {
      count       = 1
      datacenters = ["west-1"]
    }

    region "east" {
      count       = 1
      datacenters = ["east-1"]
    }

  }

  update {
    max_parallel      = 1
    min_healthy_time  = "10s"
    healthy_deadline  = "2m"
    progress_deadline = "3m"
    auto_revert       = true
    auto_promote      = true
    canary            = 1
  }


  group "cache" {

    count = 0

    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:6.0"
        ports = ["db"]
      }

      resources {
        cpu    = 256
        memory = 128
      }
    }
  }

  group "sidecar" {

    count = 0

    # set the reschedule stanza so that we don't have to wait too long
    # for the deployment to be marked failed
    reschedule {
      attempts       = 1
      interval       = "24h"
      unlimited      = false
      delay          = "5s"
      delay_function = "constant"
    }

    task "sidecar" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "/bin/sh"
        args    = ["local/script.sh"]
      }

      # this script will always fail in the east region
      template {
        destination = "local/script.sh"
        data        = <<EOH
if [[  \${NOMAD_REGION} == "east" ]]
then
echo FAIL
exit 1
fi
echo OK
sleep 600

EOH
      }

      resources {
        cpu    = 128
        memory = 64
      }
    }
  }
}
EOF

rm /root/.bash_history
touch /root/.bash_history

exit 0
