#!/bin/bash -l

set -e

grep -q "cd /root/nomad/jobs" /root/.bash_history || fail-message "You have not navigated to /root/nomad/jobs on the Nomad server yet."

grep -q "nomad job plan chat-app-dark-binary.nomad" /root/.bash_history || fail-message "You have not planned a new deployment of the chat-app job on the Nomad server yet."

grep -q "nomad job run chat-app-dark-binary.nomad" /root/.bash_history || fail-message "You have not run the rolling update of the chat-app job on the Nomad server yet."

grep -q "nomad job status chat-app" /root/.bash_history || fail-message "You have not checked the status of the rolling update of the chat-app job on the Nomad server yet."

exit 0
