#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Plan chat-app.nomad deployment
nomad job plan chat-app-dark-binary.nomad

# Run chat-app.nomad Job
nomad job run -detach chat-app-dark-binary.nomad

# Sleep
sleep 120

# Check status of chat-app Job
nomad job status chat-app

exit 0
