version: "2"
virtualmachines:
- name: nomad-server-1
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash -l
  machine_type: n1-standard-1
- name: nomad-server-2
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash -l
  machine_type: n1-standard-1
- name: nomad-server-3
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash -l
  machine_type: n1-standard-1
- name: nomad-client-1
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash -l
  machine_type: n1-standard-1
- name: nomad-client-2
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash -l
  machine_type: n1-standard-1
