#!/bin/bash -l

set -e

gcloud compute scp nomad-server-1:/root/.bash_history /root/.nomad_server_history --strict-host-key-checking no --zone "europe-west1-b"

grep -q "nomad stop -purge mysql-server" /root/.nomad_server_history || fail-message "You have not purged the mysql job"

grep -q "nomad run" /root/.nomad_server_history || fail-message "You have not run the mysql job"

exit 0