#!/bin/bash

set -euvo pipefail

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the virtual machine"
    sleep 1
done

# Ensure we always have fresh copies of the Consul 
# Enterprise license, which we store as Instruqt secrets
# We don't need a Nomad license on the clients, it fetches
# from the Nomad server once it can join

# This trick with awk keeps the contents of the secret
# environment variables from being logged
echo "Writing license files"
awk 'BEGIN {print ENVIRON["HC_CONSUL_LICENSE"]}' > /var/consul-license.hclic < /dev/null

# And restart services
echo "Restarting services"
systemctl restart consul.service
systemctl restart nomad.service

exit 0
