#!/bin/bash -l

# Write Nomad Client 2 Config
cat <<-EOF > /etc/nomad.d/nomad-client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name
name = "client2"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-2:8500"
}
EOF

# Write Consul Client 2 Config
cat <<-EOF > /etc/consul.d/consul-client2.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client2",
  "node_name": "client2",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "0.0.0.0",
  "retry_join": [
    "nomad-server-1"
  ]
}
EOF

systemctl start consul

sleep 15

systemctl start nomad

exit 0
