#!/bin/bash -l

# Make directory for mongodb mount
mkdir -p /opt/mongodb/data

# Write Nomad Client 3 Config
cat <<-EOF > /etc/nomad.d/nomad-client3.hcl
# Setup data dir
data_dir = "/tmp/nomad/client3"

# Give the agent a unique name
name = "client3"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-3:8500"
}
EOF

# Write Consul Client 3 Config
cat <<-EOF > /etc/consul.d/consul-client3.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client3",
  "node_name": "client3",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "0.0.0.0",
  "retry_join": [
    "nomad-server-1"
  ]
}
EOF

systemctl start consul

sleep 15

systemctl start nomad

exit 0
