#!/bin/bash -l

# Write Nomad Client 1 Config
cat <<-EOF > /etc/nomad.d/nomad-client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name.
name = "client1"

# Enable the client
client {
  enabled = true
}

# Consul configuration
consul {
  address = "nomad-client-1:8500"
}
EOF

# Write Consul Client 1 Config
cat <<-EOF > /etc/consul.d/consul-client1.json
{
  "ui": true,
  "log_level": "INFO",
  "data_dir": "/tmp/consul/client1",
  "node_name": "client1",
  "bind_addr": "{{ GetInterfaceIP \"ens4\" }}",
  "client_addr": "0.0.0.0",
  "retry_join": [
    "nomad-server-1"
  ]
}
EOF

systemctl start consul

sleep 15

systemctl start nomad

apt-get -y update
apt install -y --fix-missing mysql-client-core-5.7

exit 0
