#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/client1.hcl || fail-message "Have you created the acl stanza in the client1.hcl file?."

grep -q "systemctl restart nomad" /root/.bash_history || fail-message "You haven't restarted your Nomad client1 yet."

grep -q "ps -ef | grep nomad" /root/.bash_history || fail-message "You haven't performed the process check of your Nomad client1 yet."

exit 0
