#!/bin/bash -l

set -e

grep -q "acl" /root/nomad/client2.hcl || fail-message "Have you created the acl stanza in the client2.hcl file?."

grep -q "enabled = true" /root/nomad/client2.hcl || fail-message "You have not enabled acl in the client2.hcl file yet."

exit 0
