#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/client2.hcl || fail-message "You have not added the 'acl' stanza to the client2.hcl file on Client 2 yet."

grep -q "systemctl\s\+restart\s\+nomad" /root/.bash_history || fail-message "You haven't restarted Client 2 yet."

grep -q "ps\s\+-ef\s\+|\s\+grep\s\+nomad" /root/.bash_history || fail-message "You haven't performed the process check of Client 2 yet."

exit 0
