#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Check the ACL Enabled
cat <<EOF >> /etc/nomad.d/client2.hcl

# ACL Enabled
acl {
    enabled = true
}
EOF

# Restart Nomad
systemctl restart nomad

sleep 15

# Run `nomad node status`
nomad node status

# Check status with ps -ef
ps -ef | grep nomad

exit 0
