#!/bin/bash -l

# Check the ACL Enabled
cat <<EOF >> /etc/nomad.d/client1.hcl

# ACL Enabled
acl {
    enabled = true
}
EOF

# Restart Nomad
echo -e "systemctl restart nomad" >> /root/.bash_history
systemctl restart nomad

sleep 15

# Run `nomad node status`
echo -e "nomad node status" >> /root/.bash_history
nomad node status

# Check status with ps -ef
echo -e "ps -ef | grep nomad" >> /root/.bash_history
ps -ef | grep nomad

exit 0
