#!/bin/bash -l

set -e

vault_enabled=$(grep "enabled = true" /root/hashistack/nomad/server.hcl | wc -l)
if [ "$vault_enabled" -ne "2" ]; then
  fail-message "You have not enabled Vault in Nomad's server.hcl configuration file yet."
fi

token_replaced=$(grep "your nomad server token" /root/hashistack/nomad/server.hcl | wc -l)
if [ "$token_replaced" -ne "0" ]; then
  fail-message "You have not added your Vault token to Nomad's server.hcl configuration file yet."
fi

grep -q "systemctl\s\+restart\s\+nomad" /root/.bash_history || fail-message "You haven't restarted the Nomad agent yet."

exit 0
