#!/bin/bash -l

set -e

gcloud iam service-accounts keys create --iam-account service-account@$INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID.iam.gserviceaccount.com creds.json

gcloud compute scp /root/creds.json nomad-server-1:/root --zone europe-west1-b

gcloud compute ssh nomad-server-1 --zone europe-west1-b --command 'consul kv put service_account @creds.json'

cat <<-EOF > /root/nomad/controller.nomad
job "controller" {
  datacenters = ["dc1"]
  group "controller" {
    task "plugin" {
      driver = "docker"
      template {
        data = <<EOH
{{ key "service_account" }}
EOH
  destination = "secrets/creds.json"
      }
       env {
           GOOGLE_APPLICATION_CREDENTIALS = "/secrets/creds.json"
        }
      config {
        image = "gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver:v0.7.0-gke.0"
       args = [
          "--endpoint=unix:///csi/csi.sock",
          "--v=6",
          "--logtostderr",
          "--run-node-service=false"
        ]
      }
      csi_plugin {
        id        = "gcepd"
        type      = "controller"
        mount_dir = "/csi"
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
EOF

gcloud compute scp /root/nomad/controller.nomad nomad-server-1:/root/nomad/controller.nomad --strict-host-key-checking no --zone "europe-west1-b"


cat <<-EOF > /root/nomad/nodes.nomad
job "nodes" {
  datacenters = ["dc1"]
  type = "system"
  group "nodes" {
    task "plugin" {
      driver = "docker"
      template {
        data = <<EOH
{{ key "service_account" }}
EOH
  destination = "secrets/creds.json"
      }
      env {
        GOOGLE_APPLICATION_CREDENTIALS = "/secrets/creds.json"
      }
      config {
        image = "gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver:v0.7.0-gke.0"
        args = [
          "--endpoint=unix:///csi/csi.sock",
          "--v=6",
          "--logtostderr",
          "--run-controller-service=false"
        ]
        privileged = true
      }
      csi_plugin {
        id        = "gcepd"
        type      = "node"
        mount_dir = "/csi"
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
EOF

gcloud compute scp /root/nomad/nodes.nomad nomad-server-1:/root/nomad/nodes.nomad --strict-host-key-checking no --zone "europe-west1-b"

exit 0
