#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Inspect the job specification file
cat redis.nomad

# Run the Job
nomad job run redis.nomad

# Sleep
sleep 30

# Check the job status with the CLI
nomad status

# Stop the job with the CLI
nomad job stop redis

# Sleep
sleep 30

exit 0
