version: "2"
virtualmachines:
- name: nomad-server-1
  image: instruqt-hashicorp/hashistack-0-13-0
  shell: /bin/bash -l
  environment:
    CONSUL_HTTP_ADDR: 127.0.0.1:8500
  machine_type: n1-standard-1
- name: nomad-client-1
  image: instruqt-hashicorp/hashistack-0-13-0
  shell: /bin/bash -l
  environment:
    CONSUL_HTTP_ADDR: 127.0.0.1:8500
  machine_type: n1-standard-1
- name: nomad-client-2
  image: instruqt-hashicorp/hashistack-0-13-0
  shell: /bin/bash -l
  environment:
    CONSUL_HTTP_ADDR: 127.0.0.1:8500
  machine_type: n1-standard-1
- name: nomad-client-3
  image: instruqt-hashicorp/hashistack-0-13-0
  shell: /bin/bash -l
  environment:
    CONSUL_HTTP_ADDR: 127.0.0.1:8500
  machine_type: n1-standard-1
