#!/bin/bash -l

set -e

glove_result=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "mysql -h mysql-server.service.consul -u web -ppassword -D itemcollection -s -N -e \"select count(*) from items where name='glove';\"")

if [ $glove_result -ne 1 ]; then
  fail-message "The MySQL table does not contain 'glove'."
fi

exit 0
