#!/bin/bash -l

# Generate the payload.json file
echo -e "nomad job run -output redis.nomad > payload.json" >> /root/.bash_history
nomad job run -output redis.nomad > payload.json

# Run the job with the HTTP API
echo -e "curl --data @payload.json http://localhost:4646/v1/jobs" >> /root/.bash_history
curl --data @payload.json http://localhost:4646/v1/jobs

# Sleep
sleep 30

# Get the Nomad node status with HTTP API
echo -e "curl http://localhost:4646/v1/job/redis/summary" >> /root/.bash_history
curl http://localhost:4646/v1/job/redis/summary

# Stop the job with the HTTP API
echo -e "curl --request DELETE http://localhost:4646/v1/job/redis" >> /root/.bash_history
curl --request DELETE http://localhost:4646/v1/job/redis

# Sleep 30
sleep 30

exit 0
