#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Generate the payload.json file
nomad job run -output redis.nomad > payload.json

# Run the job with the HTTP API
curl --data @payload.json http://localhost:4646/v1/jobs

# Sleep
sleep 30

# Get the Nomad node status with HTTP API
curl http://localhost:4646/v1/job/redis/summary

# Stop the job with the HTTP API
curl --request DELETE http://localhost:4646/v1/job/redis

# Sleep 30
sleep 30

exit 0
