#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Run mongodb Job
nomad job run webapp.nomad

# Sleep
sleep 30

# Check mongodb job Status
nomad job status webapp

# Run chat-app Job
nomad job run traefik.nomad

# Sleep
sleep 120

# Check chat-app Status
nomad job status traefik

exit 0
