#!/bin/bash -l

set -e

consul_members=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "consul members | grep alive | wc -l")

if [ $consul_members -ne 4 ]; then
  fail-message "'consul members' does not show 4 running Consul nodes."
fi

nomad_servers=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "nomad server members | grep alive | wc -l")

if [ $nomad_servers -ne 1 ]; then
  fail-message "'cnomad server members' does not show 1 running Nomad server."
fi

nomad_clients=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "nomad node status | grep ready | wc -l")

if [ $nomad_clients -ne 3 ]; then
  fail-message "'nomad node status' does not show 3 running Nomad clients."
fi

mysql_installed=$(gcloud compute ssh nomad-server-1 --zone europe-west1-b  --project $INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID --strict-host-key-checking no --command "mysql --version | grep mysql | wc -l")

if [ $mysql_installed -ne 1 ]; then
  fail-message "'mysql --version' does not confirm that the MySQL client is installed on the Nomad server."
fi

exit 0
