#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/server3.hcl || fail-message "You have not added the 'acl' stanza to /etc/nomad.d/server3.hcl on Server 3 yet."

grep -q "authoritative_region" /etc/nomad.d/server3.hcl || fail-message "You have not set 'authoritative_region' in the server3.hcl file on Server 3 yet."

grep -q "systemctl restart nomad" /root/.bash_history || fail-message "You haven't restarted Server 3 yet."

grep -q "ps -ef | grep nomad" /root/.bash_history || fail-message "You haven't performed the process check of Server 3 yet."

exit 0
