#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/server3.hcl || fail-message "Have you created the acl stanza in the server3.hcl file?."

grep -q "authoritative_region" /etc/nomad.d/server3.hcl || fail-message "You have not enabled authoritative_region in the server3.hcl file yet."

grep -q "systemctl restart nomad" /root/.bash_history || fail-message "You haven't restarted your Nomad server3 yet."

grep -q "ps -ef | grep nomad" /root/.bash_history || fail-message "You haven't performed the process check of your Nomad server3 yet."

exit 0