#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/server2.hcl || fail-message "You have not added the 'acl' stanza to /etc/nomad.d/server2.hcl on Server 2 yet."

grep -q "authoritative_region" /etc/nomad.d/server2.hcl || fail-message "You have not set the  'authoritative_region' in the server2.hcl file on Server 2 yet."

grep -q "systemctl\s\+restart\s\+nomad" /root/.bash_history || fail-message "You haven't restarted Server 2 yet."

grep -q "ps\s\+-ef\s\+|\s\+grep\s\+nomad" /root/.bash_history || fail-message "You haven't performed the process check of Server 2 yet."

exit 0
