#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/server2.hcl || fail-message "You have not added the 'acl' stanza to /etc/nomad.d/server2.hcl on Server 2 yet."

grep -q "authoritative_region" /etc/nomad.d/server2.hcl || fail-message "You have not set the  'authoritative_region' in the server2.hcl file on Server 2 yet."

grep -q "systemctl restart nomad" /root/.bash_history || fail-message "You haven't restarted Server 2 yet."

grep -q "ps -ef | grep nomad" /root/.bash_history || fail-message "You haven't performed the process check of Server 2 yet."

exit 0
