#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/server1.hcl || fail-message "You have not added the 'acl' stanza to /etc/nomad.d/server1.hcl on Server 1 yet."

grep -q "authoritative_region" /etc/nomad.d/server1.hcl || fail-message "You have not set the  'authoritative_region' in the server1.hcl file on Server 1 yet."

grep -q "systemctl\s\+restart\s\+nomad" /root/.bash_history || fail-message "You haven't restarted Server 1 yet."

grep -q "nomad\s\+server\s\+members" /root/.bash_history || fail-message "You haven't run 'nomad server members' on Server 1 yet."

grep -q "ps\s\+-ef\s\+|\s\+grep\s\+nomad" /root/.bash_history || fail-message "You haven't performed the process check of Server 1 yet."

exit 0
