#!/bin/bash -l

set -e

grep -q "acl" /etc/nomad.d/server1.hcl || fail-message "Have you created the acl stanza in the server1.hcl file?."

grep -q "enabled = true" /etc/nomad.d/server1.hcl || fail-message "You have not enabled acl in the server1.hcl file yet."

exit 0
