#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Check the ACL Enabled
cat <<EOF >> /etc/nomad.d/server2.hcl

# ACL Enabled

acl {
    enabled = true
}
EOF

# Check Authoritive region
ex -s -c '10i|  authoritative_region = "global"' -c x /etc/nomad.d/server2.hcl

# Restart Nomad Agent
systemctl restart nomad

sleep 15

# Check Nomad Members
nomad server members

# Check the Nomad nodes
nomad node status

# Check nomad agent Running
ps -ef | grep nomad

exit 0
