#!/bin/bash -l

# Check the ACL Enabled
cat <<EOF >> /etc/nomad.d/server1.hcl

# ACL Enabled

acl {
    enabled = true
}
EOF

# Check Authoritive region
ex -s -c '10i|  authoritative_region = "global"' -c x /etc/nomad.d/server1.hcl

systemctl restart nomad

nomad server members

ps -ef | grep nomad

exit 0