#!/bin/bash -l

set -e

grep -q "consul\s\+agent\s\+-config-file\s\+consul-client2.json\s\+>\s\+consul.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your second Consul client yet."

grep -q "nomad\s\+agent\s\+-config\s\+nomad-client2.hcl\s\+>\s\+nomad.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your second Nomad client yet."

exit 0
