#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

cd nomad

# Run the Consul agent
consul agent -config-file consul-server3.json > consul.log 2>&1 &

# Sleep
sleep 15

# Check the members of the Consul cluster
consul members

# Run the Nomad server
nomad agent -config nomad-server3.hcl > nomad.log 2>&1 &

# Sleep
sleep 30

# Check the Nomad cluster members
nomad server members

# Check the Nomad nodes
nomad node status

exit 0
