#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

cd nomad

# Run the Consul agent
consul agent -config-file consul-server1.json > consul.log 2>&1 &

# Sleep
sleep 15

# Run the Nomad server
nomad agent -config nomad-server1.hcl > nomad.log 2>&1 &

exit 0
