#!/bin/bash -l

mkdir nomad

# Write Nomad Server Config
cat <<-EOF > /root/nomad/server1.hcl
# Setup data dir
data_dir = "/tmp/nomad/server1"

# Give the agent a unique name. Defaults to hostname
name = "server1"

# Enable the server
server {
  enabled = true

  # Self-elect, should be 3 or 5 for production
  bootstrap_expect = 3
}
EOF

# Write Nomad Server Config
cat <<-EOF > /root/nomad/server2.hcl
# Setup data dir
data_dir = "/tmp/nomad/server2"

# Give the agent a unique name. Defaults to hostname
name = "server2"

# Enable the server
server {
  enabled = true

  # Self-elect, should be 3 or 5 for production
  bootstrap_expect = 3
  server_join {
    retry_join = ["nomad-server-1"]
  }
}
EOF

# Write Nomad Server Config
cat <<-EOF > /root/nomad/server3.hcl
# Setup data dir
data_dir = "/tmp/nomad/server3"

# Give the agent a unique name. Defaults to hostname
name = "server3"

# Enable the server
server {
  enabled = true

  # Self-elect, should be 3 or 5 for production
  bootstrap_expect = 3
  server_join {
    retry_join = ["nomad-server-1"]
  }
}
EOF

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name. Defaults to hostname
name = "client1"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server"]
}
EOF

# Write Nomad Client 2 Config
cat <<-EOF > /root/nomad/client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name. Defaults to hostname
name = "client2"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server"]
}
EOF

# Run server1
cd nomad
nomad agent -config server1.hcl > nomad.log 2>&1 &

exit 0
