#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Check the Nomad cluster members
nomad server members

# Check the Nomad nodes
nomad node status

# Check the Nomad jobs
nomad status

exit 0
