#!/bin/bash -l

# Check the Nomad cluster members
echo -e "nomad server members" >> /root/.bash_history
nomad server members

# Check the Nomad nodes
echo -e "nomad node status" >> /root/.bash_history
nomad node status

# Check the Nomad jobs
echo -e "nomad status" >> /root/.bash_history
nomad status

exit 0
