#!/bin/bash -l

set -e

grep -q "nomad\s\+agent\s\+-config\s\+server.hcl\s\+>\s\+nomad.log\s\+2>&1\s\+&" /root/.bash_history || fail-message "You haven't run your Nomad server yet."

grep -q "nomad\s\+server\s\+members" /root/.bash_history || fail-message "You haven't checked the members of your Nomad cluster yet."

grep -q "nomad\s\+node\s\+status" /root/.bash_history || fail-message "You haven't checked the staus of your Nomad nodes (clients) yet."

exit 0
