#!/bin/bash -l

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts
HOSTNAME=$(hostname -s)
sed -i "s/127\.0\.0\.1 ${HOSTNAME}/#127.0.0.1 ${HOSTNAME}/" /etc/hosts

mkdir nomad

# Write Nomad Server Config
cat <<-EOF > /root/nomad/server.hcl
# Setup data dir
data_dir = "/tmp/nomad/server1"

# Give the agent a unique name. Defaults to hostname
name = "nomad-server"

# Enable the server
server {
  enabled = true

  # Self-elect, should be 3 or 5 for production
  bootstrap_expect = 1
}
EOF

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name. Defaults to hostname
name = "client1"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server"]
}
EOF

# Write Nomad Client 2 Config
cat <<-EOF > /root/nomad/client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name. Defaults to hostname
name = "client2"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server"]
}
EOF

cd /root/nomad

exit 0
