#!/bin/bash -l

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts and options in /etc/resolv.conf
sed -i "/${HOSTNAME}/d" /etc/hosts
sed -i '/options/d' /etc/resolv.conf

ping -c 1 nomad-server

mkdir nomad

# Write Nomad Client 2 Config
cat <<-EOF > /root/nomad/client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name. Defaults to hostname
name = "client2"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server"]
}
EOF

exit 0
