#!/bin/bash -l

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts
HOSTNAME=$(hostname -s)
sed -i "s/127\.0\.0\.1 ${HOSTNAME}/#127.0.0.1 ${HOSTNAME}/" /etc/hosts

mkdir nomad

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name. Defaults to hostname
name = "client1"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server"]
}
EOF

exit 0
