#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# cd to nomad directory
cd nomad

# Run the Nomad server
nomad agent -config server.hcl > nomad.log 2>&1 &

# Sleep
sleep 30

# Check the Nomad cluster members
nomad server members

# Check the Nomad nodes
nomad node status

# Sleep
sleep 30

exit 0
