#!/bin/bash -l

mkdir -p /home/nomad/nomad/quotas
chown -R nomad:nomad /home/nomad/nomad/quotas

# Write Default Resource Quota
cat <<-EOF > /home/nomad/nomad/quotas/quota-default.hcl
name = "default"
description = "default quota"

limit {
    region = "global"
    region_limit {
        cpu = 2300
        memory = 3100
    }
}
EOF

# Write Dev Resource Quota
cat <<-EOF > /home/nomad/nomad/quotas/quota-dev.hcl
name = "dev"
description = "dev quota"

limit {
    region = "global"
    region_limit {
        cpu = 2300
        memory = 4100
    }
}
EOF

# Write QA Resource Quota
cat <<-EOF > /home/nomad/nomad/quotas/quota-qa.hcl
name = "qa"
description = "qa quota"

limit {
    region = "global"
    region_limit {
        cpu = 2300
        memory = 4100
    }
}
EOF

exit 0
