#!/bin/bash -l

set -e

grep -q "cd /root/nomad/jobs" /root/.bash_history || fail-message "You have not navigated to /root/nomad/jobs on the Nomad server yet."

grep -q "nomad job plan chat-app-light-docker.nomad" /root/.bash_history || fail-message "You have not planned the blue/green deployment of the chat-app job on the Nomad server yet."

grep -q "nomad job run chat-app-light-docker.nomad" /root/.bash_history || fail-message "You have not run the blue/green deployment of the chat-app job on the Nomad server yet."

grep -q "nomad job status chat-app" /root/.bash_history || fail-message "You have not checked the status of the chat-app job on the Nomad server yet."

grep -q "nomad deployment promote" /root/.bash_history || fail-message "You have not promoted the blue/green deployment of the chat-app job on the Nomad server yet."

exit 0
