#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Plan a blue/green deployment of the chat-app job
nomad job plan chat-app-light-docker.nomad

# Run a blue/green deployment of the chat-app job
nomad job run -detach chat-app-light-docker.nomad

# Sleep
sleep 180

# Check the status of the blue/green deployment
nomad job status chat-app > blue-green-status.txt

# Determine the ID of the active deployment
blue_green_deployment_id=$(cat blue-green-status.txt | grep "Latest Deployment" -A1 | grep ID | cut -d'=' -f2 | cut -d' ' -f2)

# Promote the deployment
nomad deployment promote $blue_green_deployment_id

exit 0
