#!/bin/bash -l

set -e

gcloud compute scp nomad-server-1:/root/.bash_history /root/.nomad_server_history --strict-host-key-checking no --zone "europe-west1-b"

#grep -q "consul kv put" /root/.nomad_server_history || fail-message "You have written the service accoutn credentials to consul"

grep -q "nomad plugin status" /root/.nomad_server_history || fail-message "You have not checked the status of the plugin"

exit 0