#!/bin/bash -l

gcloud iam service-accounts keys create --iam-account service-account@$INSTRUQT_GCP_PROJECT_NOMAD_PROJECT_ID.iam.gserviceaccount.com creds.json

gcloud compute scp /root/creds.json nomad-server-1:/root --zone europe-west1-b

gcloud compute ssh nomad-server-1 --zone europe-west1-b --command 'mkdir nomad-csi'

gcloud compute ssh nomad-server-1 --zone europe-west1-b --command 'cat <<-EOF > nomad-csi/mysql.nomad
job "mysql-server" {
  datacenters = ["dc1"]
  type        = "service"

  group "mysql-server" {
    count = 1

    volume "mysql" {
      type      = "csi"
      read_only = false
      source    = "mysql"
    }

    restart {
      attempts = 10
      interval = "5m"
      delay    = "25s"
      mode     = "delay"
    }

    task "mysql-server" {
      driver = "docker"

      volume_mount {
        volume      = "mysql"
        destination = "/srv"
        read_only   = false
      }

      env = {
        "MYSQL_ROOT_PASSWORD" = "password"
      }

      config {
        image = "rberlind/mysql-demo:latest"
        args = ["--datadir", "/srv/mysql"]

        port_map {
          db = 3306
        }
      }

      resources {
        cpu    = 500
        memory = 1024

        network {
          port "db" {
            static = 3306
          }
        }
      }

      service {
        name = "mysql-server"
        port = "db"

        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
EOF'

gcloud compute ssh nomad-server-1 --zone europe-west1-b --command 'cat <<-EOF > nomad-csi/controller.nomad
job "controller" {
  datacenters = ["dc1"]
  group "controller" {
    task "plugin" {
      driver = "docker"
      template {
        data = <<EOH
{{ key "service_account" }}
EOH
  destination = "secrets/creds.json"
      }
       env {
           "GOOGLE_APPLICATION_CREDENTIALS" = "/secrets/creds.json"
        }
      config {
        image = "gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver:v0.7.0-gke.0"
       args = [
          "--endpoint=unix:///csi/csi.sock",
          "--v=6",
          "--logtostderr",
          "--run-node-service=false"
        ]
      }
      csi_plugin {
        id        = "gcepd"
        type      = "controller"
        mount_dir = "/csi"
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
EOF'

gcloud compute ssh nomad-server-1 --zone europe-west1-b --command 'cat <<-EOF > nomad-csi/nodes.nomad
job "nodes" {
  datacenters = ["dc1"]
  type = "system"
  group "nodes" {
    task "plugin" {
      driver = "docker"
      template {
        data = <<EOH
{{ key "service_account" }}
EOH
  destination = "secrets/creds.json"
      }
      env { "GOOGLE_APPLICATION_CREDENTIALS" = "/secrets/creds.json"
      }
      config {
        image = "gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver:v0.7.0-gke.0"
        args = [
          "--endpoint=unix:///csi/csi.sock",
          "--v=6",
          "--logtostderr",
          "--run-controller-service=false"
        ]
        privileged = true
      }
      csi_plugin {
        id        = "gcepd"
        type      = "node"
        mount_dir = "/csi"
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
EOF'

gcloud compute ssh nomad-server-1 --zone europe-west1-b --command 'cat <<-EOF > nomad-csi/volume.hcl
type = "csi"
id = "mysql"
name = "mysql"
external_id = "<< SELF LINK >>"
access_mode = "single-node-writer"
attachment_mode = "file-system"
plugin_id = "gcepd"
EOF'



exit o
