#!/bin/bash -l

set -e

grep -q "consul\s\+members" /root/.bash_history || fail-message "You have not run 'consul members' on the Server yet."

grep -q "nomad\s\+server\s\+members" /root/.bash_history || fail-message "You have not run 'nomad server members' on the Server yet."

grep -q "nomad\s\+node\s\+status" /root/.bash_history || fail-message "You have not run 'nomad node status' on the Server yet."

consul_clients=$(consul members | grep alive | wc -l)
if [ $consul_clients -ne 3 ]; then
  fail-message "There are not 3 running Consul clients."
fi

nomad_servers=$(nomad server members | grep alive | wc -l)
if [ $nomad_servers -ne 1 ]; then
  fail-message "The Nomad server is not running."
fi

nomad_clients=$(nomad node status | grep ready | wc -l)
if [ $nomad_clients -ne 2 ]; then
  fail-message "There are not 2 running Nomad clients."
fi

exit 0
