#!/bin/bash -l

# Change directory
echo -e "cd /root/hashistack/vault" >> /root/.bash_history
cd /root/hashistack/vault

# Write the Nomad policy to Vault
echo -e "vault policy write nomad-server nomad-server-policy.hcl" >> /root/.bash_history
vault policy write nomad-server nomad-server-policy.hcl

exit 0