#!/bin/bash -l

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts and options in /etc/resolv.conf
sed -i "/${HOSTNAME}/d" /etc/hosts
sed -i '/options/d' /etc/resolv.conf

# Some pings to estabish connectivity
ping -c 1 nomad-server-1
ping -c 1 nomad-server-2
ping -c 1 nomad-server-3
ping -c 1 nomad-client-1
ping -c 1 nomad-client-2

mkdir nomad

# Write Nomad Client 2 Config
cat <<-EOF > /root/nomad/nomad-client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name.
name = "client2"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server-1"]
}
EOF

exit 0
