#!/bin/bash -l

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

# Uncomment out mapping of 127.0.0.1 to hostname in /etc/hosts and options in /etc/resolv.conf
sed -i "/${HOSTNAME}/d" /etc/hosts
sed -i '/options/d' /etc/resolv.conf

# Some pings to estabish connectivity
ping -c 1 nomad-server-1
ping -c 1 nomad-server-2
ping -c 1 nomad-server-3
ping -c 1 nomad-client-1
ping -c 1 nomad-client-2

mkdir nomad

# Write Nomad Server 1 Config
cat <<-EOF > /root/nomad/nomad-server1.hcl
# Setup data dir
data_dir = "/tmp/nomad/server1"

# Give the agent a unique name.
name = "server1"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
}
EOF

# Write Nomad Server 2 Config
cat <<-EOF > /root/nomad/nomad-server2.hcl
# Setup data dir
data_dir = "/tmp/nomad/server2"

# Give the agent a unique name.
name = "server2"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
  server_join {
    retry_join = ["nomad-server-1"]
  }
}
EOF

# Write Nomad Server 3 Config
cat <<-EOF > /root/nomad/nomad-server3.hcl
# Setup data dir
data_dir = "/tmp/nomad/server3"

# Give the agent a unique name.
name = "server3"

# Enable the server
server {
  enabled = true
  bootstrap_expect = 3
  server_join {
    retry_join = ["nomad-server-1"]
  }
}
EOF

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/nomad-client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name.
name = "client1"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server-1"]
}
EOF

# Write Nomad Client 2 Config
cat <<-EOF > /root/nomad/nomad-client2.hcl
# Setup data dir
data_dir = "/tmp/nomad/client2"

# Give the agent a unique name.
name = "client2"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server-1"]
}
EOF

exit 0
