#!/bin/bash -l

set -e

#
grep -q "cd /root/nomad/jobs" /root/.bash_history || fail-message "You have not navigated to /root/nomad/jobs on the Nomad server yet."

grep -q "nomad job run webapp.nomad" /root/.bash_history || fail-message "You have not run the mongodb.nomad job on the Nomad server yet."

grep -q "nomad job status webapp" /root/.bash_history || fail-message "You have not checked the status of the mongodb job with the CLI on the Nomad server yet."

grep -q "nomad job run traefik.nomad" /root/.bash_history || fail-message "You have not run the chat-app.nomad job on the Nomad server yet."

grep -q "nomad job status traefik" /root/.bash_history || fail-message "You have not checked the status of the chat-app job on the Nomad server yet."

exit 0
