#!/bin/bash -l

set -e

grep -q "nomad run nomad/plugin-ebs-controller.nomad" /root/.bash_history || fail-message "You have not deployed the plugin. Run the controller job"

grep -q "nomad run nomad/plugin-ebs-nodes.nomad" /root/.bash_history || fail-message "You have not deployed the plugin. Run the nodes job"


exit 0
