#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

nomad job run nomad/plugin-ebs-controller.nomad

nomad job run nomad/plugin-ebs-nodes.nomad

nomad volume register /nomad/volume.hcl

exit 0
