# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
virtualmachines:
- name: nomad-server
  image: instruqt-hashicorp/hashistack-2004-0-13-1
  shell: /bin/bash -l
  machine_type: n1-standard-1
