#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Change directory
cd /root/nomad/jobs

# Plan the job
nomad job plan chat-app-dark-docker.nomad

# Run the job
nomad job run chat-app-dark-docker.nomad

# Sleep
sleep 120

# Check the status
nomad job status chat-app > canary-status.txt

# Determine the ID of the active deployment
canary_deployment_id=$(cat canary-status.txt | grep "Latest Deployment" -A1 | grep ID | cut -d'=' -f2 | cut -d' ' -f2)

# Roll back the deployment
nomad deployment fail $canary_deployment_id

exit 0
