#!/bin/bash -l

set -e

# Check that consul members was run
grep -q "sshpass\s\+-e\s\+ssh\s\+hashistack@\$nomad_server_ip" /root/.bash_history || fail-message "You have not SSHed to the Nomad server yet."

sshpass -e ssh hashistack@$nomad_server_ip 'consul members' > consul_members.txt
consul_members=$(cat consul_members.txt | grep alive | wc -l)

if [ $consul_members -ne 4 ]; then
  fail-message "'consul members' does not show 4 running Consul nodes."
fi

sshpass -e ssh hashistack@$nomad_server_ip 'nomad server members' > nomad_servers.txt
nomad_servers=$(cat nomad_servers.txt | grep alive | wc -l)

if [ $nomad_servers -ne 1 ]; then
  fail-message "'nomad server members' does not show 1 running Nomad server."
fi

sshpass -e ssh hashistack@$nomad_server_ip 'nomad node status' > nomad_clients.txt
nomad_clients=$(cat nomad_clients.txt | grep ready | wc -l)

if [ $nomad_clients -ne 3 ]; then
  fail-message "'nomad node status' does not show 3 running Nomad clients."
fi

exit 0
