#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Sleep
sleep 30

# Check Consul members
sshpass -e ssh nomad@$nomad_server_ip 'consul members'

# Check Nomad server
sshpass -e ssh nomad@$nomad_server_ip 'nomad server members'

# Check Nomad clients
sshpass -e ssh nomad@$nomad_server_ip 'nomad node status'

exit 0
