#!/bin/bash -l

HISTFILE=/root/.bash_history
set -o history

server_ip=$(ip addr show ens4 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)

ssh nomad-server-1-east "nomad server join $server_ip:4648"

sleep 5

nomad server members

nomad status -region="east"

exit 0