#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

# Navigate to /root/nomad directory
cd nomad

# Run the connect.nomad Job
nomad job run connect.nomad

# Sleep
sleep 60

exit 0
