#!/bin/bash -l

set -e

grep -q "nomad agent -config server.hcl > nomad.log 2>&1 &" /root/.bash_history || fail-message "You haven't run your Nomad server yet."

grep -q "nomad server members" /root/.bash_history || fail-message "You haven't checked the members of your Nomad cluster yet."

grep -q "nomad node status" /root/.bash_history || fail-message "You haven't checked the staus of your Nomad nodes (clients) yet."

grep -q "nomad job init -short" /root/.bash_history || fail-message "Please create the sample Nomad Job specification file first."

exit 0
