#!/bin/bash -l

mkdir nomad

# Write Nomad Client 1 Config
cat <<-EOF > /root/nomad/nomad-client1.hcl
# Setup data dir
data_dir = "/tmp/nomad/client1"

# Give the agent a unique name.
name = "client1"

# Enable the client
client {
    enabled = true
    servers = ["nomad-server-1"]
}
EOF

exit 0
