#!/bin/bash -l

#Enable bash history
HISTFILE=~/.bash_history
set -o history

cd nomad

# Run the Nomad server
nomad agent -config nomad-server3.hcl > nomad.log 2>&1 &

# Check the Nomad cluster members
nomad server members

# Check the Nomad nodes
nomad node status

# Sleep
sleep 30

exit 0
