# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/field-workshops-nomad/deploy-nomad-and-portworx
on: workflow_dispatch
jobs:
  this-is-so-stupid:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bogus workflow for testing in IL-577"
